"""add graph checkpoints.

Revision ID: d8318c85d3bd
Revises: a207787632e6
Create Date: 2026-08-27 21:50:48.136243
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'd8318c85d3bd'
down_revision: str | None = 'a207787632e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'graph_checkpoints',
        sa.Column('graph_thread_id', sa.String(length=200), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('state_payload', sa.JSON(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('graph_thread_id'),
    )
    op.create_index(
        'ix_graph_checkpoints_user_updated_at',
        'graph_checkpoints',
        ['user_id', 'updated_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_graph_checkpoints_user_updated_at',
        table_name='graph_checkpoints',
    )
    op.drop_table('graph_checkpoints')
    # ### end Alembic commands ###
